### ISSUE TITLE
Bad example, it does not work

### ISSUE THREAD

**Issue by sekrett** [lagartoflojo/sensu-plugins-telegram#28]
I spent a lot of time to figure out why sensu was not sending notifications to telegram. I tried a sample data from command line to be sure this handler works, and it works, but the handler itself should be configured in a different way:

```json
{
  "handlers": {
    "default": {
      "type": "pipe",
      "command": "handler-telegram.rb"
    }
  }
}
```

If one is expert enough, he will change the configuration to his needs.

Also it is not clear why do you add a filter? Is it required? Looks like it is not.

**Comment by lagartoflojo** [comment]
Hi,
Thanks for your feedback.

Regarding the `"default"` key, if you look at other handlers like [Slack](https://github.com/sensu-plugins/sensu-plugins-slack) or [Hipchat](https://github.com/sensu-plugins/sensu-plugins-hipchat), you'll see that giving the handler a specific name is how it has been standardized across other Sensu handlers.

Regarding the `"filter"`, it's necessary as of "[Deprecating Event Filtering in sensu-plugin](https://blog.sensu.io/deprecating-event-filtering-in-sensu-plugin-b60c7c500be3)" if you use any type of filtering in your checks (which honestly, you want to do, unless you want to suffer from [alert fatigue](https://blog.sensu.io/alert-fatigue-part-1-avoidance-and-course-correction)).

**Comment by sekrett** [comment]
Ok, make sense. Thanks for the explanation.

In general Sensu documentation is hard to understand. To do one thing you have to read some extra pages located in different places.

Maybe adding a check example, which specifies what handler to use, will help just to get started? Is it redundant?

**Comment by lagartoflojo** [comment]
I updated the readme with more info, I hope that it's clearer now :)

**Comment by sekrett** [comment]
I wanted to help you but did it better. Now it is perfectly clear, thanks.
