### ISSUE TITLE
Sensu 0.29

### ISSUE THREAD

**Issue by alexwbaule** [lagartoflojo/sensu-plugins-telegram#3]
With sensu 0.29, the handler dont work, the sensu change the API.

**Comment by Pshellvon** [comment]
With SENSU_VERSION=1.5.0-1 does not work too...

**Comment by lagartoflojo** [comment]
I used the [Sensu Sandbox](https://github.com/sensu/sandbox/tree/master/sensu/core#set-up-the-sandbox) with the latest Sensu 1.6.1, and the Telegram handler works perfectly fine.

I will close this for now, but if you still have problems, please post the entire logs of the error you are seeing, as well as the versions of Sensu, the sensu-plugin gem and the sensu-plugins-telegram gem.
