### ISSUE TITLE
Transfer Gem ownership on rubygems.org

### ISSUE THREAD

**Issue by majormoses** [lagartoflojo/sensu-plugins-telegram#5]
Looks like we need to get ownership or we can't deploy.

**Comment by majormoses** [comment]
@lagartoflojo could you please make Sensu_Plugins an owner so we can push to rubygems.org

**Comment by lagartoflojo** [comment]
Done: https://rubygems.org/gems/sensu-plugins-telegram

**Comment by majormoses** [comment]
@lagartoflojo thanks.
