### ISSUE TITLE
Rest-Client 1.8 is incompatible with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by ushis** [lagartoflojo/sensu-plugins-telegram#7]
Rest-Client 1.8 is incompatible with OpenSSL 1.1.0. See:

- https://github.com/rest-client/rest-client/pull/573
- https://github.com/rest-client/rest-client/issues/569

Please update the rest-client dependency to 2.0.2

**Comment by majormoses** [comment]
@ushis thanks for the report, any chance you could submit a PR for this?
